vim.keymap.set("n", ";", ":", { noremap = true })
vim.keymap.set("n", "<leader>e", ":Ex<cr>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>h", ":rightbelow term<cr>i", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>n", ":set number!<cr>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>s", ":set list!<cr>", { noremap = true, silent = true })
vim.keymap.set("n", "<c-h>", "<c-w>h", { noremap = true, silent = true })
vim.keymap.set("n", "<c-j>", "<c-w>j", { noremap = true, silent = true })
vim.keymap.set("n", "<c-k>", "<c-w>k", { noremap = true, silent = true })
vim.keymap.set("n", "<c-l>", "<c-w>l", { noremap = true, silent = true })
vim.keymap.set("t", "<c-j>", "<c-\\><c-n><c-w>j", { noremap = true, silent = true })
vim.keymap.set("t", "<c-k>", "<c-\\><c-n><c-w>k", { noremap = true, silent = true })
vim.keymap.set("t", "<c-h>", "<c-\\><c-n><c-w>h", { noremap = true, silent = true })
vim.keymap.set("t", "<c-l>", "<c-\\><c-n><c-w>l", { noremap = true, silent = true })
