#!/bin/sh
touchpad_line=$(xinput list --name-only | grep Touchpad)
touchpad_name=$(printf "%s" "$touchpad_line" | tr -d '∼' | xargs)

case "$touchpad_line" in
	'∼'*) xinput enable  "$touchpad_name" ;;
	*)    xinput disable "$touchpad_name"  && xdotool mousemove 9999 9999
esac
